<?php
/*function student_detail(){
    if (arg(1) && is_numeric(arg(1))) {
        $result = db_select('registration_form', 'nf')
            ->fields('nf')
            ->condition('sid', arg(1), '=')
            ->execute()
            ->fetchAssoc();
    }       
    $file = file_load($result['profilepic']);
    $uri = $file->uri;
    $url = file_create_url($uri);

    $output = "<div class='container'>
                <div class='student-image'>
                    <img src='".$url."'></img>
                </div>
                <div class='student-name'>".$result['name']."</div>
                <div class='student-mothername'>".$result['mother_name']."</div>
                <div class='student-fathername'>".$result['father_name']."</div>
                <div class='student-image'>".$result['address']."</div>
                <div class='student-image'>".$result['email']."</div>
                <div class='student-image'>".$result['mobile']."</div>
                <div class='student-image'>".$result['steam']."</div>
            </div>";
    print_r($output);
}*/
?>
